### ISSUE TITLE
(node:17) UnhandledPromiseRejectionWarning: TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by firaxis** [FeliceGeracitano/webperf-dashboard#10]
Hi, thanks for this application.

I'm trying to run it, but getting some error that leads to empty dashboard.
So, I've checked out master branch, run
`docker-compose up --build`
on a second terminal
>declare -a arr_desk=(
>                     "https://www.saksfifthavenue.com"
>                     "https://www.lordandtaylor.com"
>                     "https://www.thebay.com"
>                     "https://www.saksoff5th.com"
>                     "https://shop.nordstrom.com"
>                     "https://www.macys.com"
>                     "https://www.neimanmarcus.com"
>                     "https://www.bloomingdales.com"
>                   );

>for i in "${arr[@]}";
>                  do curl --request POST --url http://localhost:3000/collect-one --header "Content-Type: application/json" --data "{ \"url\": \"$i\", \"report\": true }";
>                 done;

And watching logs in "docker-compose" terminal:

>=======CUT=======
> webperf-dashboard-lighthouse_1  | [Audit tools]: Successfully got data for https://www.saksfifthavenue.com
> influxdb_1                      | [httpd] 172.18.0.5 - root [13/Feb/2019:15:44:17 +0000] "POST /write?db=lighthouse&p=%5BREDACTED%5D&precision=n&rp=&u=root HTTP/1.1" 404 47 "-" "-" 38a7053d-2fa6-11e9-8001-0242ac120002 14437
> webperf-dashboard-lighthouse_1  | [APP Collect-One Endpoint]: Audit for https://www.lordandtaylor.com with HTML Report.
> webperf-dashboard-lighthouse_1  | [Audit tools]: Getting data for https://www.lordandtaylor.com
> webperf-dashboard-lighthouse_1  | [Audit tools]: chromeFlags: ["--headless","--no-sandbox","--no-zygote","--disable-gpu"]
> webperf-dashboard-lighthouse_1  | (node:17) UnhandledPromiseRejectionWarning: TypeError: Converting circular structure to JSON
> webperf-dashboard-lighthouse_1  |     at JSON.stringify (<anonymous>)
> webperf-dashboard-lighthouse_1  |     at Object.<anonymous> (/usr/src/webperf-dashboard-lighthouse/build/influxdb.js:47:75)
> webperf-dashboard-lighthouse_1  |     at Generator.throw (<anonymous>)
> webperf-dashboard-lighthouse_1  |     at rejected (/usr/src/webperf-dashboard-lighthouse/build/influxdb.js:5:65)
> webperf-dashboard-lighthouse_1  |     at process.internalTickCallback (internal/process/next_tick.js:77:7)
> webperf-dashboard-lighthouse_1  | (node:17) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
> webperf-dashboard-lighthouse_1  | (node:17) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
>=======CUT=======

This is what I see in terminal with curl:
>{"performance-score":0.02,"best-practices-score":0.64,"pwa-score":0.31,"accessibility-score":0.56,"seo-score":1,"estimated-input-latency":768.7999999999971,"estimated-input-latency-score":0,"first-contentful-paint":7241.240999999998,"first-contentful-paint-score":0.08,"first-cpu-idle":24973.07299999999,"first-cpu-idle-score":0,"first-meaningful-paint":8007.467499999999,"first-meaningful-paint-score":0.05,"interactive":29018.82399999999,"interactive-score":0,"speed-index":14869.307459217398,"speed-index-score":0.01,"dom-size":5327,"dom-size-score":0,"errors-in-console":1,"errors-in-console-score":0,"offscreen-images":3510,"offscreen-images-score":0.18,"redirects":2167.836,"redirects-score":0.33,"time-to-first-byte":965.265,"time-to-first-byte-score":0,"total-byte-weight":3396428,"total-byte-weight-score":0.72,"unminified-css":0,"unminified-css-score":1,"unminified-javascript":150,"unminified-javascript-score":0.88,"uses-passive-event-listeners":false,"uses-passive-event-listeners-score":0,"uses-text-compression":150,"uses-text-compression-score":0.88,"network-requests":240,"network-requests-score":null,"dom-max-depth":20,"dom-max-child-elements":92}

Could you suggest where to look or how to fix it ?

**Comment by FeliceGeracitano** [comment]
Hi @firaxis,
Thanks for reporting.
By mistake i've upgraded the lighthouse version of the docker container. Check out the reverted master branch and let me know.

I'm working on a new version deployable via Kubernetes that will simplify the cloud deployment as well

**Comment by firaxis** [comment]
Fixed.
Many thanks!
