### ISSUE TITLE
Cannot GET / on EC2

### ISSUE THREAD

**Issue by krishnakanthpps** [FeliceGeracitano/webperf-dashboard#7]
I setup and EC2 instance and cloned the git and ran the commands, but I am unable to access the port 0. 

for port 80 : I get connection refused.

for port 3000: I get "Cannot GET /".

Looks like something needs to be fixed inside the yaml file. Being a newbie on Docker, would you be able to help?

**Comment by FeliceGeracitano** [comment]
Hi @krishnakanthpps 
I'm not very familiar with EC2 instances in AWS but I guess you need to configure security groups and create access to those ports

**Comment by FeliceGeracitano** [comment]
@krishnakanthpps
I've upgraded the infrastructure to use Kubernetes. (if you have docker for OSX you can install Kubernetes it in few clicks.)

Run the deploy_local.sh script
`https://github.com/FeliceGeracitano/webperf-dashboard/blob/master/scripts/deploy_local.sh`

Will be much easier to publish on a provider such google cloud or aws.
I deployed successfully my cluster on gpc (google cloud platform), I'll write some documentation soon

**Comment by krishnakanthpps** [comment]
@FeliceGeracitano  Thank you so much. I will try this out soon.
